# Site settings
title: Dmitry Chopey
email: dmitry.chopey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        Passionate web developer who likes creating interesting and
        unusual solutions with clear and maintainable code
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dmitry-chopey.com" # the base hostname & protocol for your site
twitter_username: DmitryChopey
github_username:  dmitrychopey

# Build settings
markdown: kramdown
gems:
  - octopress-image-tag 
